object Main extends App {
  var human = new Human("Андрей")
  human.say_hello()
  var employee = new Employee("Миша")
  employee.working()
  employee.say_hello()
  var worker = new Worker("Вадим")
  worker.working()
  worker.mood()
  var student = new Student
  student.study()
  var librarian = new Librarian("Дима")
  librarian.say_hello()
  var director = new Director("Сергей")
  director.working()
  var staff = new Staff(employee)
  staff.add_employer(employee)
  staff.work()
  var guard = new Guard("Максим")
  guard.working()
  var cashier = new Cashier("Давид")
  cashier.working()
  var workingPlace = new WorkingPlace
  workingPlace.set_employer(employee)
  workingPlace.get_employer()
  var cabinet = new Cabinet(152,100)
  cabinet.set_employer(director)
  cabinet.get_employer()
}
